export const CALENDAR_REQUEST = 'CALENDAR_REQUEST';
export const CALENDAR_SUCCES = 'CALENDAR_SUCCES';
export const CALENDAR_FAIL = 'CALENDAR_FAIL';

export const STORED_CALENDAR_REQUEST = 'STORED_CALENDAR_REQUEST';
export const STORED_CALENDAR_SUCCES = 'STORED_CALENDAR_SUCCES';
export const STORED_CALENDAR_FAIL = 'STORED_CALENDAR_FAIL';

export const ADD_SHIFT = "ADD_SHIFT";
export const CHANGE_CALENDARSHIFT_TYPE = 'CHANGE_CALENDARSHIFT_TYPE';

export const SET_SAVED_CALENDAR = 'SET_SAVED_CALENDAR';