export const ADD_AMOUNT_OF_OPERATOR_SHIFTS_FOR_NON_OPERATOR_FOR_NEXT_MONTH= "ADD_AMOUNT_OF_OPERATOR_SHIFTS_FOR_NON_OPERATOR_FOR_NEXT_MONTH";
export const ADD_AMOUNT_OF_OPERATOR_SHIFTS_FOR_OPERATOR_FOR_NEXT_MONTH= "ADD_AMOUNT_OF_OPERATOR_SHIFTS_FOR_OPERATOR_FOR_NEXT_MONTH";

export const ADD_AMOUNT_OF_OPERATOR_SHIFTS_FOR_NON_OPERATOR = "ADD_AMOUNT_OF_OPERATOR_SHIFTS_FOR_NON_OPERATOR";
export const ADD_AMOUNT_OF_OPERATOR_SHIFTS_FOR_OPERATOR = "ADD_AMOUNT_OF_OPERATOR_SHIFTS_FOR_OPERATOR";

export const ADD_POTENTIAL_CHANGE_TO_OPERATOR_SHIFT = "ADD_POTENTIAL_CHANGE_TO_OPERATOR_SHIFT";

export const STEP_3_BETA_INITIAL = "STEP_3_BETA_INITIAL";

export const STEP_5_BETA_INITIAL = "STEP_5_BETA_INITIAL";

export const UPDATE_OPERATOR_NIGHT = "UPDATE_OPERATOR_NIGHT";
export const UPDATE_OPERATOR_WEEKEND = "UPDATE_OPERATOR_WEEKEND";
export const RESET_OPERATORS_NIGHT_AND_WEEKEND = "RESET_OPERATORS_NIGHT_AND_WEEKEND";

export const WEEK_STRUCTURES_LIST_REQUEST = 'WEEK_STRUCTURE_LIST_REQUEST';
export const WEEK_STRUCTURES_LIST_SUCCES = 'WEEK_STRUCTURE_LIST_SUCCES';
export const WEEK_STRUCTURES_LIST_FAIL = 'WEEK_STRUCTURE_LIST_FAIL';

export const ADD_WEEK_STRUCTURE_REQUEST = 'ADD_WEEK_STRUCTURE_REQUEST';
export const ADD_WEEK_STRUCTURE_SUCCES = 'ADD_WEEK_STRUCTURE_SUCCES';
export const ADD_WEEK_STRUCTURE_FAIL = 'ADD_WEEK_STRUCTURE_FAIL';

export const REMOVE_WEEK_STRUCTURE_REQUEST = 'REMOVE_WEEK_STRUCTURE_REQUEST';
export const REMOVE_WEEK_STRUCTURE_SUCCES = 'REMOVE_WEEK_STRUCTURE_SUCCES';
export const REMOVE_WEEK_STRUCTURE_FAIL = 'REMOVE_WEEK_STRUCTURE_FAIL';

export const CHANGE_WEEK_STRUCTURE_REQUEST = 'CHANGE_WEEK_STRUCTURE_REQUEST';
export const CHANGE_WEEK_STRUCTURE_SUCCES = 'CHANGE_WEEK_STRUCTURE_SUCCES';
export const CHANGE_WEEK_STRUCTURE_FAIL = 'CHANGE_WEEK_STRUCTURE_FAIL';