export const EMPLOYEES_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST';
export const EMPLOYEES_LIST_SUCCES = 'EMPLOYEE_LIST_SUCCES';
export const EMPLOYEES_LIST_FAIL = 'EMPLOYEE_LIST_FAIL';

export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCES = 'ADD_EMPLOYEE_SUCCES';
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL';

export const REMOVE_EMPLOYEE_REQUEST = 'REMOVE_EMPLOYEE_REQUEST';
export const REMOVE_EMPLOYEE_SUCCES = 'REMOVE_EMPLOYEE_SUCCES';
export const REMOVE_EMPLOYEE_FAIL = 'REMOVE_EMPLOYEE_FAIL';

export const CHANGE_EMPLOYEE_REQUEST = 'CHANGE_EMPLOYEE_REQUEST';
export const CHANGE_EMPLOYEE_SUCCES = 'CHANGE_EMPLOYEE_SUCCES';
export const CHANGE_EMPLOYEE_FAIL = 'CHANGE_EMPLOYEE_FAIL';