export const SHIFTTYPE_LIST_REQUEST = 'SHIFTTYPE_LIST_REQUEST';
export const SHIFTTYPE_LIST_SUCCES = 'SHIFTTYPE_LIST_SUCCES';
export const SHIFTTYPE_LIST_FAIL = 'SHIFTTYPE_LIST_FAIL';

export const ADD_SHIFTTYPE_REQUEST = 'ADD_SHIFTTYPE_REQUEST';
export const ADD_SHIFTTYPE_SUCCES = 'ADD_SHIFTTYPE_SUCCES';
export const ADD_SHIFTTYPE_FAIL = 'ADD_SHIFTTYPE_FAIL';

export const REMOVE_SHIFTTYPE_REQUEST = 'REMOVE_SHIFTTYPE_REQUEST';
export const REMOVE_SHIFTTYPE_SUCCES = 'REMOVE_SHIFTTYPE_SUCCES';
export const REMOVE_SHIFTTYPE_FAIL = 'REMOVE_SHIFTTYPE_FAIL';

export const CHANGE_SHIFTTYPE_REQUEST = 'CHANGE_SHIFTTYPE_REQUEST';
export const CHANGE_SHIFTTYPE_SUCCES = 'CHANGE_SHIFTTYPE_SUCCES';
export const CHANGE_SHIFTTYPE_FAIL = 'CHANGE_SHIFTTYPE_FAIL';