export const CONTRACT_LIST_REQUEST = 'CONTRACT_LIST_REQUEST';
export const CONTRACT_LIST_SUCCES = 'CONTRACT_LIST_SUCCES';
export const CONTRACT_LIST_FAIL = 'CONTRACT_LIST_FAIL';


export const ADD_CONTRACT_REQUEST = 'ADD_CONTRACT_REQUEST';
export const ADD_CONTRACT_SUCCES = 'ADD_CONTRACT_SUCCES';
export const ADD_CONTRACT_FAIL = 'ADD_CONTRACT_FAIL';

export const REMOVE_CONTRACT_REQUEST = 'REMOVE_CONTRACT_REQUEST';
export const REMOVE_CONTRACT_SUCCES = 'REMOVE_CONTRACT_SUCCES';
export const REMOVE_CONTRACT_FAIL = 'REMOVE_CONTRACT_FAIL';

export const CHANGE_CONTRACT_REQUEST = 'CHANGE_CONTRACT_REQUEST';
export const CHANGE_CONTRACT_SUCCES = 'CHANGE_CONTRACT_SUCCES';
export const CHANGE_CONTRACT_FAIL = 'CHANGE_CONTRACT_FAIL';