export const CALENDARS_OVERVIEW_LIST_REQUEST = 'CALENDARS_OVERVIEW_LIST_REQUEST';
export const CALENDARS_OVERVIEW_LIST_SUCCES = 'CALENDARS_OVERVIEW_LIST_SUCCES';
export const CALENDARS_OVERVIEW_LIST_FAIL = 'CALENDARS_OVERVIEW_LIST_FAIL';

export const CALENDAR_SHIFTS_REQUEST = 'CALENDAR_SHIFTS_REQUEST';
export const CALENDAR_SHIFTS_SUCCES = 'CALENDAR_SHIFTS_SUCCES';
export const CALENDAR_SHIFTS_FAIL = 'CALENDAR_SHIFTS_FAIL';

export const CHANGE_CALENDARSHIFT_TYPE = 'CHANGE_CALENDARSHIFT_TYPE';

export const ADD_SHIFT = "ADD_SHIFT";

export const SAVE_CALENDAR_SHIFTS_REQUEST = 'SAVE_CALENDAR_SHIFTS_REQUEST';
export const SAVE_CALENDAR_SHIFTS_SUCCES = 'SAVE_CALENDAR_SHIFTS_SUCCES';
export const SAVE_CALENDAR_SHIFTS_FAIL = 'SAVE_CALENDAR_SHIFTS_FAIL';